Update `formatPatternMap` to correctly interpret `%u`
goccy/go-zetasqlite pull request #126
Opened 2023-10-31 19:28 UTC by philschoefer

See title

2023-12-07 03:59 UTC, goccy commented on internal/function_time_parser.go
> +	return []rune(fmt.Sprintf("%d", int(t.Weekday()))), nil
please use `[]rune(fmt.Sprint(int(t.Weekday())))`

2023-12-07 04:00 UTC, goccy requested changes

2023-12-07 04:00 UTC, goccy commented on internal/function_time_parser.go
> +	return []rune(fmt.Sprintf("%d", int(t.Weekday()))), nil
please use []rune(fmt.Sprint(int(t.Weekday())))

2023-12-21 16:19 UTC, philschoefer commented
Thank you! Updated, please re-review ❤️

2024-01-26 01:07 UTC, ohaibbq requested changes

2024-01-26 01:07 UTC, ohaibbq commented on internal/function_time_parser.go
> +	return []rune(fmt.Sprint(int(t.Weekday())))
Thanks for the update @philschoefer 
It looks like the build is failing as you're no longer returning a `nil` error

By the way, I'm not a project member, so I won't have permission to approve / get this merged.
We'll need to wait for @goccy

2024-03-09 15:07 UTC, closed without merging

2024-03-09 15:07 UTC, goccy commented
Due to lack of response, this PR is closed