Implement DATE_DIFF by week
goccy/go-zetasqlite pull request #91
Opened 2023-03-01 19:25 UTC by marcosapmf

main

2023-03-13 03:36 UTC, goccy requested changes
Thank you for your contribution, but test failed

2023-03-13 13:08 UTC, marcosapmf commented
Hi @goccy!
Just fixed in ee6659d2ac7db0bc9613e7924f88ed9c82384df7
Thanks!

2023-03-14 05:24 UTC, goccy approved these changes

2023-03-14 05:25 UTC, goccy commented
LGTM, Thank you !!

2023-03-14 05:25 UTC, merged